name: Python tests
on: [ push ]
env:
  GITHUB_ACTIONS: 1

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.7 ]
      fail-fast: false

    env:
      LANG: "C.UTF-8"

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Setup PostgreSQL With Init Scripts
        uses: m4nu56/postgresql-action@1.0
        with:
          postgresql db: celeryTest
          postgresql user: celeryTest
          postgresql password: celeryTest
      - name: Run Tox py-django31-drf3_12
        run: tox -e py-django31-drf3_12

